# Multi-Model Configuration Example: Mixed GPT-4 and Claude-3-Sonnet
# This example shows how to configure an experiment with 5 GPT-4 and 5 Claude agents
# WARNING: This is an experimental feature. Enable at your own risk.

# Basic experiment parameters
NUM_AGENTS: 10
NUM_ROUNDS: 5
NUM_ITERATIONS_PER_ROUND: 10
MAX_MESSAGE_HISTORY: 5
TEMPERATURE: 0.7

# Enable multi-model support (experimental feature)
ENABLE_MULTI_MODEL: true

# Model configurations
# Define available models and their parameters
model_configs:
  openai/gpt-4:
    model_type: openai/gpt-4
    api_key_env: OPENROUTER_API_KEY  # Uses default key
    max_tokens: 1500
    temperature: 0.7
    rate_limit: 60  # requests per minute
    retry_delay: 1.0
    custom_params:
      top_p: 0.95
  
  anthropic/claude-3-sonnet-20240229:
    model_type: anthropic/claude-3-sonnet-20240229
    api_key_env: OPENROUTER_API_KEY  # Can override with CLAUDE_API_KEY if needed
    max_tokens: 1500
    temperature: 0.7
    rate_limit: 50  # Claude may have different rate limits
    retry_delay: 1.2
    custom_params:
      top_p: 0.9

# Scenario definitions
# Each scenario specifies how many agents use each model
scenarios:
  - name: Balanced GPT-4 and Claude
    model_distribution:
      openai/gpt-4: 5                          # 5 agents use GPT-4
      anthropic/claude-3-sonnet-20240229: 5    # 5 agents use Claude

# Default models for backward compatibility
MAIN_MODEL: google/gemini-2.5-flash  # Used when multi-model disabled
SUB_MODEL: openai/gpt-4.1-mini      # Used for subagent decisions

# Logging configuration
LOG_LEVEL: INFO
SAVE_AGENT_RESPONSES: true
SAVE_GAME_HISTORY: true

# API configuration
API_BASE_URL: https://openrouter.ai/api/v1/chat/completions
API_TIMEOUT: 30
API_MAX_RETRIES: 3

# Output configuration
OUTPUT_DIR: results
EXPERIMENT_NAME: mixed_gpt4_claude_experiment

# Notes:
# - Agent model assignments are shuffled to prevent clustering
# - If a model fails, the system will fall back to the default model
# - Monitor experiment_errors.log for model-specific issues